SCREEN_WIDTH = 800  # 窗口宽度
SCREEN_HEIGHT = 800  # 窗口高度
MARGIN = 50  # 边距

GRID_ROWS = 10
GRID_COLS = GRID_ROWS

BLOCK_WIDTH = (SCREEN_WIDTH - MARGIN * 2) // GRID_COLS

BLOCK_SCALE = BLOCK_WIDTH / 200  # 素材宽度有参差，大体为200px
BLOCK_BACKGROUND_SCALE = BLOCK_WIDTH / 64  # 素材为64px的正方形
